# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather-Test-Leboncoin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 5.0.0-rc.3'

  # Pods for Weather-Test-Leboncoin

  target 'Weather-Test-LeboncoinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Weather-Test-LeboncoinUITests' do
    # Pods for testing
  end

end
